### ISSUE TITLE
Update bundler in base docker container

### ISSUE THREAD

**Issue by nvick** [concord-consortium/rigse#452]
_From @benjaminwood on April 9, 2018 22:18_

Base container is: concordconsortium/docker-rails-base-ruby-2.2.6

Currently the base image has bundler 1.14.5. We ran into issues with this version that appear to be resolved in 1.14.6.

We should upgrade to at least 1.14.6, if not latest 1.16.x.

Ref: https://github.com/concord-consortium/docker-rails-base/blob/ruby22/Dockerfile

_Copied from original issue: hintmedia/rigse#1_

**Comment by benjaminwood** [comment]
This has been completed (by @scytacki I believe). Version `1.16.4` is now installed.
