### ISSUE TITLE
Extend test coverage

### ISSUE THREAD

**Issue by nvick** [concord-consortium/rigse#462]
_From @benjaminwood on April 10, 2018 17:30_

Test coverage is very low and should be extended.

**Simplecov report on rspec suite:**

* All Files (62.88%)
* Controllers (46.26%)
* Models (77.6%)
* Mailers (100.0%)
* Helpers (68.0%)
* Libraries (75.64%)
* Ungrouped (75.74%)

**Simplecov report on cucumber suite (via firefox):**

* All Files (46.32%) 
* Controllers (27.71%) 
* Models (64.21%) 
* Mailers (100.0%) 
* Helpers (55.97%) 
* Libraries (61.61%) 
* Ungrouped (55.14%)

_Copied from original issue: hintmedia/rigse#10_

**Comment by benjaminwood** [comment]
We spiked on this for a week and extended coverage by ~6%. Closing this for now.
