### ISSUE TITLE
Organize specs

### ISSUE THREAD

**Issue by nvick** [concord-consortium/rigse#464]
_From @benjaminwood on April 10, 2018 18:40_

I found some capybara integration specs in a controller specs file. I'm not sure how much more of this sort of thing there is, but some effort should be made to ensure that specs are properly organized/categorized.

Example:

https://github.com/hintmedia/rigse/blob/748311842563874f7b1ed575700822ca079d10da/spec/controllers/investigations_controller_otml.rb#L53-L63

_Copied from original issue: hintmedia/rigse#12_

**Comment by benjaminwood** [comment]
I think we're good here.
