### ISSUE TITLE
Update ActiveRecord Syntax (Deprecated Finders)

### ISSUE THREAD

**Issue by nvick** [concord-consortium/rigse#466]
_From @benjaminwood on April 10, 2018 19:19_

All dynamic methods except for find_by_... and find_by_...! are deprecated.

* 48 occurrences of `find_all_by_`
* 150 occurrences of `find_or_create_by_`.
* 87 occurrences of `find(:all....)`
* 154 uses of `:conditions =>` in various contexts (lots of scopes with conditions)
* 43 occurrences of `:order =>`

Under Rails 4, the [activerecord-deprecated_finders](https://github.com/rails/activerecord-deprecated_finders) gem can be used to but our recommendation is to resolve these issue in advance of the 4.x upgrade.

_Copied from original issue: hintmedia/rigse#14_

**Comment by benjaminwood** [comment]
The plan of attack here is to:

1. Discover which occurrences are hit by the test suite
2. Update syntax for those that have test coverage
3. Create a report/list of occurrences that are not hit by the test suite for @scytacki to review before taking next steps.

My thought is that we can discover which occurrences are hit by the test suite by replacing them with an exception. Upon running the tests, any occurrences that do not raise the exception are not hit by the test suite. Kind of like mutation testing. :smile: 

Might be easier to use simple-cov? Not sure.

**Comment by tjchambers** [comment]
With the work on scopes in #473 I have cleaned up a number of the above implicitly, given that the generated specs I made weeks ago cover scopes I know they should have test coverage. So once PR #606 is merged I can begin to tackle the remainder of the above. 

First I would change those occurrences in spec modules (*spec.rb) - since those are 100% executed. Then I can embark on the process of only changing those covered by a spec. using a technique similar to what @benjaminwood described above.

**Comment by tjchambers** [comment]
As of the today:

* 40 occurrences of `find_all_by_`
* 110 occurrences of `find_or_create_by_`.
* 70 occurrences of `find(:all....)`
* 107 uses of `:conditions =>` in various contexts (lots of scopes with conditions)
* 7 occurrences of `:order =>` fixable

**Comment by benjaminwood** [comment]
Gotcha, thanks!

**Comment by tjchambers** [comment]
Down to 10 `find_or_create_by_` occurrences - 2 in comments, 1 in migrations, leaving only 7 of those to review. However I have one cucumber spec that is failing. So I need to trace that.

**Comment by tjchambers** [comment]
As of today: 
- 7 occurrences of `find_all_by_` (4 in site_notices_controller, 2 in inports_controller, 1 in fixups.rake)
- 6 occurrences of `find_or_create_by_` in various controllers and process_external_activities_job.rb
- 1 occurrence of `find(:all)` in rig_se model folder (ignore?)
- 4 references to `:conditions` all in has_many or has_one (change when we get to Rails 4.0)
- 25 occurrences of `:order =>` all in has_many (change when we get to Rails 4.0)

I could tackle trying to add more coverage in the controllers, etc. to address the remaining `find_`issues. THoughts?

**Comment by tjchambers** [comment]
@scytacki your thoughts on next steps?

**Comment by tjchambers** [comment]
I believe this is as addressed as it will be until converting to Rails 4.0. @benjaminwood feel free to close if you concur.

**Comment by benjaminwood** [comment]
Agreed! Nice work.
