### ISSUE TITLE
Upgrade rubyzip gem

### ISSUE THREAD

**Issue by benjaminwood** [concord-consortium/rigse#605]
@lbondaryk writes:

> known moderate severity security vulnerability detected in rubyzip <= 1.2.1 defined in Gemfile.lock.
> Gemfile.lock update suggested: rubyzip ~> 1.2.2.

**Comment by tjchambers** [comment]
Started looking into this, but the axlsx gem is the holdup. It looks like the changelog is not complete (leaped to 3.0.0.-pre). Not sure what is in rubygems either. But that is the inhibiting gem, and if it is updated it may be incompatible with other gems.

**Comment by benjaminwood** [comment]
Looks like `axlsx` is only used here in [`Reports::Book`](https://github.com/concord-consortium/rigse/blob/master/app/services/reports/book.rb). @scytacki is there a chance this code is no longer in use? If so, the solution to upgrading `rubyzip` may be simple. :smile:

**Comment by tjchambers** [comment]
Looks like nokogiri was bumped to 1.8.4 so I will revisit this again.
