### ISSUE TITLE
Upgrade FactoryGirl -> FactoryBot

### ISSUE THREAD

**Issue by benjaminwood** [concord-consortium/rigse#611]
We had deferred this upgrade, but @tjchambers knows a good bit about this migration so it may be worth while to tackle it while he's on the project.

**Comment by tjchambers** [comment]
My approach would be to fix the Factory singleton usage to use FactoryGirl correctly and remove that deprecation, and PR that. Then a second step to FactoryBot.

**Comment by benjaminwood** [comment]
Makes sense to me!

**Comment by tjchambers** [comment]
merged in #623
